Update AWS ALB security policies for 2023.3.22
mozilla/ssl-config-generator pull request #198
Opened 2023-04-24 21:04 UTC by kepstin

From this accouncement:
https://aws.amazon.com/about-aws/whats-new/2023/03/application-load-balancer-tls-1-3/ TLSv1.3 support is now generally available in AWS ALB. They have added a new set of security policies that enable TLSv1.3. I have selected the following policies which are the closest fit to the Mozilla server side TLS recommendations:

**Old:**
Remains `TLS-1-0-2015-04`. This policy doesn't support TLSv1.3, but it is the only policy available which supports DES-CBC3-SHA.

**Intermediate:**
Switched from `FS-1-2-Res-2019-08` to `TLS13-1-2-2021-06`. These two policies support the same set of TLSv1.2 ciphers, but the newer one also adds TLSv1.3 support.

**Modern:**
Can be supported now, using `TLS13-1-3-2021-06`.

2023-09-14 05:37 UTC, chalbersma commented
I'd like to +1 these recommendations it looks like it matches [AWS's updated docs](https://docs.aws.amazon.com/elasticloadbalancing/latest/network/create-tls-listener.html) on the subject too.

2024-02-02 17:58 UTC, janbrasna requested changes
@kepstin The `intermediate` policy chosen includes weak ciphers from `old`, there might be better match:

2024-02-02 17:58 UTC, janbrasna commented on src/templates/partials/awsalb.hbs
> +      SslPolicy: {{#if (includes "TLSv1" output.protocols)}}ELBSecurityPolicy-TLS-1-0-2015-04{{else}}{{#if (includes "TLSv1.2" output.protocols)}}ELBSecurityPolicy-TLS13-1-2-2021-06{{else}}ELBSecurit
```suggestion
      SslPolicy: {{#if (includes "TLSv1" output.protocols)}}ELBSecurityPolicy-TLS-1-0-2015-04{{else}}{{#if (includes "TLSv1.2" output.protocols)}}ELBSecurityPolicy-TLS13-1-2-Res-2021-06{{else}}ELBSecurityPolicy-TLS13-1-3-2021-06{{/if}}{{/if}}
```

2024-10-04 18:25 UTC, janbrasna approved these changes
Thanks @kepstin for the update — I've added the suggestions myself to match the current specs unblocking this PR, it should be released to production soon. 🚀 

The TLS v1.3 support is a great addition — thank you for contributing it!

2024-10-04 20:00 UTC, gstrauss approved these changes

2024-10-04 20:01 UTC, merged