Update openssl
mozilla/ssl-config-generator pull request #263
Opened 2024-10-12 05:06 UTC by gstrauss

Update openssl

Depends on #256 

Created for https://github.com/mozilla/ssl-config-generator/pull/256#issuecomment-2408072818

2024-10-13 09:02 UTC, gstrauss commented
Note, if any profiles recommend DHE ciphers, then should add a comment about configuring key size limits to avoid resource attacks which negotiate very large key sizes?  See #162

2024-11-07 18:19 UTC, janbrasna requested changes
The biggest impact is perhaps that OpenSSL 3.x adds support for FFDH exchange in TLSv1.3, basically bringing back the never-ending performance/DoS issue #162 officially also to `modern` (and other configs even when we remove DHE-RSA suites).

See https://openssl-library.org/post/2022-10-21-tls-groups-configuration/

Before releasing this as the new default, we should either consider configuring bit size limits (=restrict RFC7919 groups) to avoid malicious clients negotiating unreasonably large key exchanges, or basically just update the upstream wording from "curves" to "groups" to only include EC curves in RFC7919/RFC8446 negotiations, and rule out any `ffdhe*` handshakes.

2024-11-07 18:19 UTC, janbrasna commented on src/js/configs.js
> +    latestVersion: '3.3.2',
The 3.4.0 should now include additional DHEattack CVEs fixed, FYI:

```suggestion
    latestVersion: '3.4.0',
```

2024-11-25 08:02 UTC, gstrauss commented
> Before releasing this as the new default, we should either consider configuring bit size limits (=restrict RFC7919 groups) to avoid malicious clients negotiating unreasonably large key exchanges, or basically just update the upstream wording from "curves" to "groups" to only include EC curves in RFC7919/RFC8446 negotiations, and rule out any ffdhe* handshakes.

That is being discussed in #270 Explicitly configure curves/groups from the guidelines

---

The issue I have with making #270 a blocking issue for this is that people are already using OpenSSL 3.x, as all versions of OpenSSL prior to OpenSSL 3.0 are now EOL.  Yes, some people are still running older versions of OpenSSL, but anyone maintaining their software is not running older versions.

2024-12-06 00:11 UTC, gstrauss commented
Included in #281

2024-12-06 00:11 UTC, closed without merging